"""
Extract task IDs by error type from pipeline output CSVs.
Run from: Pipeline construction/AST+DYNMAIC+LIB_API/
Output: error_type_ids.py with ERROR_TYPE_IDS dict (task_ids per error type per dataset).
If a task has multiple error types, it appears in multiple lists.

Uses error_types column when filled; otherwise falls back to parsing dynamic_info.error_type
and ast_info.ast_errors (mbpp often has empty error_types).
"""
import ast
import json
import os

import pandas as pd

# Same normalization as PHASE_1 get_repair_category
def _normalize(s):
    t = s.split(":")[-1].strip() if ":" in s else s.strip()
    return t.replace(" ", "")

def _extract_error_types_from_row(row):
    """Get error type string from row: prefer error_types column, else parse dynamic_info and ast_info."""
    et = row.get("error_types", "")
    if et is not None and str(et).strip() and str(et) != "nan":
        return str(et)
    # Fallback: parse dynamic_info.error_type and ast_info.ast_errors
    parts = []
    # dynamic_info
    dinfo = row.get("dynamic_info", "")
    if dinfo is not None and isinstance(dinfo, str) and dinfo.strip():
        try:
            d = ast.literal_eval(dinfo)
            if isinstance(d, dict):
                etype = d.get("error_type", "")
                if etype and str(etype).strip():
                    parts.append(str(etype))
        except (ValueError, SyntaxError):
            pass
    # ast_info (syntax/indentation)
    ainfo = row.get("ast_info", "")
    if ainfo is not None and isinstance(ainfo, str) and ainfo.strip():
        try:
            a = ast.literal_eval(ainfo)
            if isinstance(a, dict) and a.get("ast_parsed") is False:
                parts.append("SyntaxError")
            else:
                ast_errors = a.get("ast_errors", []) if isinstance(a, dict) else []
                for err in ast_errors:
                    etype = err.get("type", "") if isinstance(err, dict) else ""
                    if etype:
                        parts.append(etype)
        except (ValueError, SyntaxError):
            pass
    return ",".join(parts) if parts else ""

def _get_categories_for_error_types(error_types_str):
    """Return set of categories (syntax, attribute, type, name, key, assertion, timeout, other) for this row."""
    if not error_types_str or not str(error_types_str).strip():
        return set()
    parts = [p.strip() for p in str(error_types_str).split(",")]
    cats = set()
    for p in parts:
        t = _normalize(p)
        if t in ("SyntaxError", "IndentationError"):
            cats.add("syntax")
        elif t in ("AttributeError", "attribute_error"):
            cats.add("attribute")
        elif t == "TypeError":
            cats.add("type")
        elif t in ("NameError", "name_error"):
            cats.add("name")
        elif t == "KeyError":
            cats.add("key")
        elif t in ("AssertionError", "WrongAnswer"):
            cats.add("assertion")
        elif t == "TimeoutError":
            cats.add("timeout")
        else:
            cats.add("other")
    return cats

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    ds1000 = pd.read_csv(os.path.join(base, "ds1000_pipeline_output.csv"))
    humaneval = pd.read_csv(os.path.join(base, "humaneval_pipeline_output.csv"))
    mbpp = pd.read_csv(os.path.join(base, "mbpp_pipeline_output.csv"))

    datasets = {
        "ds1000": ds1000,
        "humaneval": humaneval,
        "mbpp": mbpp,
    }

    # category -> dataset -> list of task_ids
    by_category = {}
    for cat in ["syntax", "attribute", "type", "name", "key", "assertion", "timeout", "other"]:
        by_category[cat] = {"ds1000": [], "humaneval": [], "mbpp": []}

    for ds_name, df in datasets.items():
        failed = df[df["status"] == "hallucinated"]
        for _, row in failed.iterrows():
            task_id = row["task_id"]
            error_types_str = _extract_error_types_from_row(row)
            cats = _get_categories_for_error_types(error_types_str)
            for cat in cats:
                if task_id not in by_category[cat][ds_name]:
                    by_category[cat][ds_name].append(task_id)

    out_path = os.path.join(base, "error_type_ids.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by extract_by_error_type.py. Run that script to regenerate.\n\n")
        f.write("ERROR_TYPE_IDS = ")
        f.write(repr(by_category))
        f.write("\n")

    print("error_type_ids.py generated successfully!")
    for cat, d in by_category.items():
        total = sum(len(v) for v in d.values())
        print(f"  {cat}: ds1000={len(d['ds1000'])}, humaneval={len(d['humaneval'])}, mbpp={len(d['mbpp'])} (total={total})")

if __name__ == "__main__":
    main()
